### PR TITLE
Added Zapier to the list

### PR DESCRIPTION
**Pull request by matiasburni**

### CODE REVIEW

**Comment by smoya** [comment]
@matiasburni Mr Burni please can you help us figuring out if this is valid? 😅

**Comment by matiasburni** [comment]
Sorry for the delay, yes Zapier created an entity in Spain, so now they hire as a full-time employee. 
I can't reopen it, but I can resubmit a MR if required.

Hola Sergio ✋

**Comment by smoya** [comment]
> Sorry for the delay, yes Zapier created an entity in Spain, so now they hire as a full-time employee. I can't reopen it, but I can resubmit a MR if required.
> 
> Hola Sergio ✋

No prob! I knew you would answer just after closing the PR! 🤣 
I see what you say and also we can confirm by checking https://docs.google.com/document/d/1VzesvLsgVG2RDRPtGvBF8CbcB9ZA-Hsddg0P2ildBb8/edit#heading=h.m30k825hwucj

So, +1 on my side to add Zapier to the list cc @alexpdp7 

Nice to see you around here @matiasburni ! Tons of good memories 😄

**Comment by alexpdp7** [comment]
OK, I have some conflicts, but even this offer:

https://zapier.com/jobs/7019093002/head-of-revenue-and-growth-engineering/

shows some salary ranges for Spain, so merging...

**Pull request merged**
