### PR TITLE
Added Genially

### PR DESCRIPTION
**Pull request by Linkaynn**

### CODE REVIEW

**Comment by alexpdp7** [comment]
Hi,

Thanks for your PR. We have seen a couple of PRs with a couple of things we would prefer to clarify and discuss before merging, so we've made a small extension to the README:

https://github.com/remote-es/remotes#offers

Quoting:

> Please provide a stable URL which lists all offers that meet the conditions for being listed in this page (or a simple way to filter/locate them).
>
> We recommend:
>
> * Not using an URL or page that seems to be for a specific offer (e.g. /blog/backend_python_dev). People browsing the list might not feel confident that the offer is still available and up to date
> * Showing clearly when offers were posted

Do you have a better job posting page, with dates of offers and which do not seem to indicate a single offer? I did some digging and I was surprised to see:

https://genial.ly/work-with-us

, but the offer you link in the PR is not in that page (!).

Could you provide a better job listing? We are afraid that people might not click on your link as they might fear the offer is outdated, etc.

Cheers,

Álex

**Comment by alexpdp7** [comment]
@Linkaynn I see that:

https://genial.ly/work-with-us

, now lists the backend dev position, but it's not clear that the position is remote.

Also contacted rrhh@genial.ly:

> Some time ago, we received a request to add your company to our list ( https://github.com/remote-es/remotes/pull/29 ), but looking at:
>
> https://genial.ly/work-with-us
>
> It is not clear which of those positions are available to people looking for remote jobs in Spain under a Spanish contract.
>
> Do you have such positions available? If so, how could someone find out which ones are those?

If we do not receive feedback, we will close this PR.

**Comment by alexpdp7** [comment]
Closing due to lack of feedback.

**Comment by alexpdp7** [comment]
BTW, pinging @Linkaynn . I see that your LinkedIn jobs listing has offers which clearly state you offer remote, even though your main careers site is not clear about that (of course, it also never seems to specify a location... but that's not really obvious?).

Do you think you could clarify a bit your jobs page, or should we use your LinkedIn job offers listing to add you?

**Comment by Linkaynn** [comment]
@alexpdp7 sorry for not answering the doubts last year, I was not be notified about your two responses.

In Genially, tech jobs are offered as fully remote. I think that is better to link to the LinkedIn job listing.

**Comment by alexpdp7** [comment]
Excellent, thank you! I was going to request uesteibar's approval, as I've been relying on my personal criteria too much, but I see he thumbs-upped your message, and I'll assume that's an approval; so merging.

Thanks for following up on this and your patience, and good luck.

**Pull request merged**
