### PR TITLE
Adding Blarlo

### PR DESCRIPTION
**Pull request by davidlg**

### CODE REVIEW

**Comment by alexpdp7** [comment]
I see you posted the offer on LinkedIn too:

https://www.linkedin.com/company/blarlo/jobs/

Wouldn't that link be better? If you publish further offers they should appear at that URL automatically.

**Comment by uesteibar** [comment]
Hi @davidlg! 👋 

I understand this link is a one-time offer, do you instead have a page where we can see remote open positions at your company at any time?

**Comment by uesteibar** [comment]
race condition 😆 what @alexpdp7 said sounds good to me 👍

**Comment by davidlg** [comment]
Yeah guys you are right. 

I've updated the link and the content of the linked Github repo. In the repo we list all the positions at this moment, in the future if we add more the repo will be updated with the new positions.

I prefer to use the Github link instead of linkedin because I don't know how much time the offer will be active in linkedin.

**Comment by alexpdp7** [comment]
Thanks! Merged!

**Pull request merged**
