### PR TITLE
Add Delitbee

### PR DESCRIPTION
**Pull request by elikohen**
Delitbee is a full remote startup

### CODE REVIEW

**Comment by uesteibar** [comment]
hey @alexpdp7, I see the URL actually re-directs to one specific job posting, are we alright with that?

@elikohen what does this URL usually redirect to? is there a listing of all the positions somewhere? If there is, I think it'd best to link to that instead

**Comment by elikohen** [comment]
What a quick review! Thnx for that!

Yup, it usually links to all the open positions but right now it's the only one we have, that's why the redirect.

Whenever we'll add new ones that one won't redirect and will be the index for all the positions

**Comment by uesteibar** [comment]
that sounds fine to me then 👍

**Comment by alexpdp7** [comment]
Sounds good to me, thanks!

**Pull request merged**
