### PR TITLE
Setup review lottery for PRs

### PR DESCRIPTION
**Pull request by uesteibar**
Sometimes I don't notice or get a notification when we get a new PR, it would be great if we could assign a reviewer automatically.

Using https://github.com/uesteibar/reviewer-lottery

### CODE REVIEW

**Comment by uesteibar** [comment]
> I believe that taking decisions "alone" is a bad idea and this project was important to me enough to believe that I should justify well my decisions and argue them with someone else

yep I do agree with this, I still believe on discussing with all of you on relevant things, but I wanted to add this to share a bit the load of more mundane tasks :)

---

Let's wait until @acroca agrees to be on the lottery, then we can move forward 🚀

**Comment by acroca** [comment]
Hey,

Personally I'd rather not be in the list, I will feel bad if I get an issue assigned and, for some reason, it's not a good time to jump into it.
And, to be honest I don't think we need to assign reviews Whoever sees the notification and have time to review should be able to do it.

I don't know how you handle notifications, but if you use e-mail and have silenced gh notifications, maybe you can set an e-mail filter to get them in the inbox or something. In my case I use gh notifications for work, so I never miss them. But I left them unread until I have time to check. I also have a widget on my polybar with the notification counts, and I check very often during the working day.

**Comment by uesteibar** [comment]
It seems you both feel similarly about handling the load without a formal process, so I'll close this 👍 thanks for considering!

**Comment by alexpdp7** [comment]
It's good, and I learned about your action, looks very cool!

**Pull request closed without merging**
