### PR TITLE
adding Stuart

### PR DESCRIPTION
**Pull request by alexvaque**
Adding Stuart Company

### CODE REVIEW

**Comment by alexpdp7** [comment]
Thanks!

I've seen that only the "Barcelona, Spain" positions seem to list remote working as an option. Would only the "Barcelona, Spain" positions allow Spanish people to work remotely under a Spanish contract?

Also, can you confirm that when a Stuart offer says:

> Work-life balance - work from home and flexible hours

this follows our repo's criteria of:

> We will only list companies which allow working fully remotely (e.g. you can work from anywhere in Spain and you do not have to set foot in an office if you don't want to). Some occasional travelling for onboarding, team building or similar purposes is fine.

? Just confirming because often "work from home" means "one day a week" and those offers do not fall into the purpose of this repo.

**Comment by alexpdp7** [comment]
Sent an email to info.clients@stuart.com:

> Some time ago, we received a request to add your company to our list ( https://github.com/remote-es/remotes/pull/28 ), but looking at:
>
> https://stuart.com/careers/
>
> It is not clear which of those positions are available to people looking for remote jobs in Spain under a Spanish contract.
>
> Do you have such positions available? If so, how could someone find out which ones are those?

If we get no response from that or from @alexvaque , I'll close the PR.

**Comment by uesteibar** [comment]
maybe @naoisegolden can clarify this?

**Comment by naoisegolden** [comment]
Hello @alexpdp7 et al! Naoise here, from Stuart.

Stuart is remote-first and remote-friendly. Most engineering teams are either full remote (like Platform, which is the biggest one) or partly remote. For non-remotes, most of the product design and development happens in the Barcelona office. Work-from-home is allowed some day(s) a week, and flexitime means you can come in and out when you prefer as long as working hours should from 10:00 to 17:00.

For bureaucratic restrictions, currently only residents of the cities where we have headquarters can be hired (remote or non-remote), so France, UK and Spain right now. So as long as you are in any of these countries, you can work remotely.

Hope this helps! You can check some posts on out culture and engineering teams in the blog here https://stuart.com/blog

**Comment by naoisegolden** [comment]
LGTM 😉

**Comment by alexpdp7** [comment]
Merged.

I would encourage you guys to be clearer on the job listing, but I think we have quorum on agreeing that it's good enough for inclusion.

**Pull request merged**
