### PR TITLE
add APIUX

### PR DESCRIPTION
**Pull request by jacintoobispomarquez**

### CODE REVIEW

**Comment by alexpdp7** [comment]
Do you mind if we change the URL to:

https://www.linkedin.com/company/api-ux/jobs/

(happy to do it myself too...)

**Comment by jacintoobispomarquez** [comment]
Hi Alex,

Thanks for your interest. The problem with the link you suggest is that it includes works from other countries besides Spain related to other APIUX subsidiaries.


What do you think?

Regards,


________________________________
De: Alex Corcoles ***@***.***>
Enviado: jueves, 10 de agosto de 2023 15:54
Para: remote-es/remotes ***@***.***>
Cc: jacintoobispomarquez ***@***.***>; Author ***@***.***>
Asunto: Re: [remote-es/remotes] add APIUX (PR #139)


Do you mind if we change the URL to:

https://www.linkedin.com/company/api-ux/jobs/

(happy to do it myself too...)

**Comment by alexpdp7** [comment]
Oh, I don't think it's a problem. People can always click through and filter, I think. That kind of links with ids and all always makes me worry they will become invalid at some point.

**Comment by jacintoobispomarquez** [comment]
OK! Your experience is important, so let's go with that.

Please, merge the change yourself as you offered to us, we apreciate it!


________________________________
De: Alex Corcoles ***@***.***>
Enviado: jueves, 10 de agosto de 2023 16:13
Para: remote-es/remotes ***@***.***>
Cc: jacintoobispomarquez ***@***.***>; Author ***@***.***>
Asunto: Re: [remote-es/remotes] add APIUX (PR #139)


Oh, I don't think it's a problem. People can always click through and filter, I think. That kind of links with ids and all always makes me worry they will become invalid at some point.

**Comment by alexpdp7** [comment]
Thanks!

**Pull request closed without merging**
