### PR TITLE
Update README.md with Devo

### PR DESCRIPTION
**Pull request by miguelsalva**

### CODE REVIEW

**Comment by alexpdp7** [comment]
I see that the company has a Spanish office, so I assume it does Spanish contracts.

However, I must ask: are you absolutely sure that all positions can be done remotely from Spain? For example "Director, Public Sector Sales" or "Senior Software Engineer - Backend (Noida, India)", are you sure those will accept applicants living in Spain?

We normally use the "all offers are remote" when job listings are unclear. However, in general it's preferrable if the job listings page is *clear*. It's completely fine if some positions are remote and others are not, but for the sake of saving time, it's best if the company makes it clear which offers you "can" apply to.

**Comment by miguelsalva** [comment]
Yep, it does Spanish contracts. All positions for Spain are remote but I can't tell about those in other locations. 

Do you want me to remove the (All offers are remote) tag?

**Comment by alexpdp7** [comment]
How about "All positions in Spain are remote"?

The idea is to make it easy for people to "filter" the offers they can apply to. I would encourage talking with the team that maintains the job listing to see if they can make improvements, but of course we are happy with any text that makes things clear.

(Sometimes we do "all technical offers are remote". But this is not a fixed set- if you can think of a sentence that works, go ahead!)

**Comment by miguelsalva** [comment]
That's great! I'll be closing this MR and pushing a new one with that tag!

**Pull request closed without merging**
