### PR TITLE
Add Electromaps

### PR DESCRIPTION
**Pull request by andacata**

### CODE REVIEW

**Comment by alexpdp7** [comment]
Hi,

The link is to a blog entry from February 2019. Are you sure it's the best link? I'm not sure people will feel comfortable applying to something with date nearly a full year old (it's natural to think that either the place has already been covered... or that something is not going well if it takes nearly a year to cover it).

If you know that the company publishes offers in a particular job search portal, a search URL link there would be fine. Also, if maybe you are part of the company or in touch with them... if they are using Wordpress or something like that, they could create a tag/category, put that article there and create a link to the tag/category...

Cheers,

Álex

**Comment by andacata** [comment]
Hi, I'm part of the Electromaps team.

It's a continuous offer, we always lack people, so it has not been modified.

While I discuss your advice with the team, I think this post can be given as valid, and I will make the modification when there are changes.

Best,
Ángel.

**Comment by alexpdp7** [comment]
@andacata did you have a conversation with your team?

If the company cannot make changes, I can merge your change. However, I'd prefer if you added something like:

> (Link is a job posting from early 2019, but it is a continuous offer)

at the end of the line. If you prefer, I can make the change myself (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork )

Note that while we don't have serious policies yet, if people using the repo complain that companies have outdated information or do not comply with the rules, we will probably have to address the complaints. Without further clarification, I think it's likely that people will look at the offer and think "this offer is a year old, it's probably not worth applying".

**Comment by andacata** [comment]
@alexpdp7 We have modified the offer and updated the publication date.

**Comment by alexpdp7** [comment]
I think the more recent date will be "OK" for a while. Hopefully it will be kept up to date or you will send us a PR if the URL changes or whatever.

**Comment by andacata** [comment]
Thanks @alexpdp7

**Pull request merged**
